### ISSUE TITLE
Recommended approach for playing nicely with existing crash frameworks

### ISSUE THREAD

**Issue by theextremeprogrammer** [jflinter/JRFMemoryNoodler#1]
Jack - First of all thank you for this contribution to the community! I had also read the FB article and wanted to take a crack at this but having seen that you already did that, I thought I would give yours a shot and send a PR should I find something else that I needed from it. 

I work across various teams and projects that utilize a variety of crash reporting tools but Fabric (Crashlytics) and HockeyApp are the two primary ones. You provided some general guidance for playing nicely with existing crash frameworks which is very helpful:

_"crashDetector is a little funnier. So, the way most crash reporting frameworks work is by using a method called NSSetUncaughtExceptionHandler, which takes a pointer to a function that iOS will call when your app has triggered an uncaught exception and is about to crash (most crash reporters will then try and figure out what has gone wrong and write it to disk so they can log it to a server or something later). Unfortunately, this can only point to a single function, so if JRFMemoryNoodler were to use it to figure out if the app is recovering from a crash, it would break any crash reporting frameworks. Since if you are interested in this memory profiling, you are almost certainly using a crash reporting framework, this would be a Bad Thing. So, the crashDetector param is a block that lets you ask your crash reporting framework if it has any crashes to report. You can leave it nil, in which case JRFMemoryNoodler will set up a very very simple crash reporter of its own, but you probably don't want this."_

My assumption is that by passing 'nil' into the initializer for the JRFMemoryNoodler that it won't be able to accurately detect that the app is being opened after having experienced a crash, which is why it is necessary to know this information.

For HockeyApp, at least on version 3.8.2, it looks like they have exposed this boolean value very easily and the following implementation should be sufficient:

`[JRFMemoryNoodler beginMonitoringMemoryEventsWithHandler:^(BOOL wasInForeground) {`
`...`
`} crashDetector:^BOOL{`
`return [BITHockeyManager sharedHockeyManager].crashManager.didCrashInLastSession;`
`}];`

Question #1: Can you confirm the above approach matches your expectations?

However for Fabric/Crashlytics I'm not finding any kind of similar API except for their delegate implementation which seems like it could be really sticky to try and implement with relation to your callback. Maybe something along the lines of:
- Initialize Crashlytics framework; register delegate class
- Initialize a class property (e.g. boolean didCrash) to NO. 
- In 'crashlyticsDidDetectReportForLastExecution:', update the didCrash class property to YES if a crash was detected.
- Initialize the JRFMemoryNoodler and return the value of the didCrash class property for the crash detector block.

My only concern with this approach is ensuring the timing - can I confidently assume that the Crashlytics delegate will fire and update this property before getting to the JRFMemoryNoodler initialization call? 

If you have integrated this with Crashlytics and have a recommended approach it would be great to hear some of your thoughts on this topic. 

Thanks again for your contribution and taking the time to look this question over!

Best,

Derek

**Comment by theextremeprogrammer** [comment]
I just noticed the following line in the Crashlytics API documentation for the crashlyticsDidDetectReportForLastExecution: method:

_This is called synchronously on Crashlytics initialization._

So I'm thinking that the above approach should work but would still appreciate your thoughts on this. Thanks!

**Comment by jflinter** [comment]
Hey @derekleeapp - yeah, that's exactly what I suggest doing (in fact, I reference that HockeyApp method in the documentation for `JRFMemoryNoodler` - see https://github.com/jflinter/JRFMemoryNoodler/blob/master/JRFMemoryNoodler/JRFMemoryNoodler.h#L21).

Unfortunately, I'm not familiar with the Crashlytics API, but that approach sounds reasonable to me.

**Comment by theextremeprogrammer** [comment]
Thanks for the quick response @jflinter! Looks like I missed that reference in the .h file - apologies for my oversight there.

In case it is helpful for you or others, here's what I came up with for Crashlytics which so far in testing seems to be working as expected:

Declaration of the Crashlytics delegate:

``` objective-c
@interface XYZAppDelegate () <CrashlyticsDelegate>
```

Define a property to track whether a crash occurred or not:

``` objective-c
@property (assign, nonatomic) BOOL reportedCrashForLastExecution;
```

Initialize the property in didFinishLaunchingWithOptions:

``` objective-c
    // Set the default value and let the Crashlytics delegate update this if needed.
    self.reportedCrashForLastExecution = NO;
```

Implement the Crashlytics delegate method:

``` objective-c
- (void)crashlyticsDidDetectReportForLastExecution:(CLSReport *)report
                                 completionHandler:(void (^)(BOOL submit))completionHandler
{
    // Track internally that the app crashed during the last execution.
    self.reportedCrashForLastExecution = YES;

    if (completionHandler) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
            // The completionHandler takes a boolean value which determines if the crash report is submitted to Crashlytics or not. If desired additional logic can be added here to not submit crash reports for specific situations.
            // ** IMPORTANT: If the completion handler is not called with a value of "YES" then the crash report is not submitted to Crashlytics. **
            completionHandler(YES);
        });
    }
}
```

Return this value for the JRFMemoryNoodler crashDetector:

``` objective-c
    [JRFMemoryNoodler beginMonitoringMemoryEventsWithHandler:^(BOOL wasInForeground) {
        ...
    } crashDetector:^BOOL{
        return self.reportedCrashForLastExecution;
    }];
```

**Comment by jflinter** [comment]
Cool, glad you got things working. Let me know if this project ends up being useful to you!

—
